/**
 * Base oficial dos 399 municípios do Paraná (fonte: IBGE).
 * Usada para:
 *  - autocomplete de fixação geo-segmentada no editor
 *  - parser "cidades separadas por vírgula"
 *  - resolução cidade → região editorial (Vozes)
 */

export type Municipio = { slug: string; name: string; region: string | null };

// total: 399
export const PARANA_MUNICIPIOS = [
  { slug: "abatia", name: "Abati\u00e1", region: "norte-pioneiro" },
  { slug: "adrianopolis", name: "Adrian\u00f3polis", region: "metropolitana" },
  { slug: "agudos-do-sul", name: "Agudos do Sul", region: "metropolitana" },
  { slug: "almirante-tamandare", name: "Almirante Tamandar\u00e9", region: "metropolitana" },
  { slug: "altamira-do-parana", name: "Altamira do Paran\u00e1", region: "centro-ocidental" },
  { slug: "alto-parana", name: "Alto Paran\u00e1", region: "noroeste" },
  { slug: "alto-paraiso", name: "Alto Para\u00edso", region: "noroeste" },
  { slug: "alto-piquiri", name: "Alto Piquiri", region: "noroeste" },
  { slug: "altonia", name: "Alt\u00f4nia", region: "noroeste" },
  { slug: "alvorada-do-sul", name: "Alvorada do Sul", region: "norte-central" },
  { slug: "amapora", name: "Amapor\u00e3", region: "noroeste" },
  { slug: "ampere", name: "Amp\u00e9re", region: "sudoeste" },
  { slug: "anahy", name: "Anahy", region: "oeste" },
  { slug: "andira", name: "Andir\u00e1", region: "norte-pioneiro" },
  { slug: "antonina", name: "Antonina", region: "litoral" },
  { slug: "antonio-olinto", name: "Ant\u00f4nio Olinto", region: "centro-sul" },
  { slug: "apucarana", name: "Apucarana", region: "norte-central" },
  { slug: "arapongas", name: "Arapongas", region: "norte-central" },
  { slug: "arapoti", name: "Arapoti", region: "campos-gerais" },
  { slug: "arapua", name: "Arapu\u00e3", region: "norte-central" },
  { slug: "araruna", name: "Araruna", region: "centro-ocidental" },
  { slug: "araucaria", name: "Arauc\u00e1ria", region: "metropolitana" },
  { slug: "ariranha-do-ivai", name: "Ariranha do Iva\u00ed", region: "norte-central" },
  { slug: "assai", name: "Assa\u00ed", region: "norte-pioneiro" },
  { slug: "assis-chateaubriand", name: "Assis Chateaubriand", region: "oeste" },
  { slug: "astorga", name: "Astorga", region: "norte-central" },
  { slug: "atalaia", name: "Atalaia", region: "norte-central" },
  { slug: "balsa-nova", name: "Balsa Nova", region: "metropolitana" },
  { slug: "bandeirantes", name: "Bandeirantes", region: "norte-pioneiro" },
  { slug: "barbosa-ferraz", name: "Barbosa Ferraz", region: "centro-ocidental" },
  { slug: "barra-do-jacare", name: "Barra do Jacar\u00e9", region: "norte-pioneiro" },
  { slug: "barracao", name: "Barrac\u00e3o", region: "sudoeste" },
  { slug: "bela-vista-da-caroba", name: "Bela Vista da Caroba", region: "sudoeste" },
  { slug: "bela-vista-do-paraiso", name: "Bela Vista do Para\u00edso", region: "norte-central" },
  { slug: "bituruna", name: "Bituruna", region: "centro-sul" },
  { slug: "boa-esperanca", name: "Boa Esperan\u00e7a", region: "centro-ocidental" },
  { slug: "boa-esperanca-do-iguacu", name: "Boa Esperan\u00e7a do Igua\u00e7u", region: "sudoeste" },
  { slug: "boa-ventura-de-sao-roque", name: "Boa Ventura de S\u00e3o Roque", region: "centro-sul" },
  { slug: "boa-vista-da-aparecida", name: "Boa Vista da Aparecida", region: "oeste" },
  { slug: "bocaiuva-do-sul", name: "Bocai\u00fava do Sul", region: "metropolitana" },
  { slug: "bom-jesus-do-sul", name: "Bom Jesus do Sul", region: "sudoeste" },
  { slug: "bom-sucesso", name: "Bom Sucesso", region: "norte-central" },
  { slug: "bom-sucesso-do-sul", name: "Bom Sucesso do Sul", region: "sudoeste" },
  { slug: "borrazopolis", name: "Borraz\u00f3polis", region: "norte-central" },
  { slug: "braganey", name: "Braganey", region: "oeste" },
  { slug: "brasilandia-do-sul", name: "Brasil\u00e2ndia do Sul", region: "noroeste" },
  { slug: "cafeara", name: "Cafeara", region: "norte-central" },
  { slug: "cafelandia", name: "Cafel\u00e2ndia", region: "oeste" },
  { slug: "cafezal-do-sul", name: "Cafezal do Sul", region: "noroeste" },
  { slug: "california", name: "Calif\u00f3rnia", region: "norte-central" },
  { slug: "cambara", name: "Cambar\u00e1", region: "norte-pioneiro" },
  { slug: "cambira", name: "Cambira", region: "norte-central" },
  { slug: "cambe", name: "Camb\u00e9", region: "norte-central" },
  { slug: "campina-grande-do-sul", name: "Campina Grande do Sul", region: "metropolitana" },
  { slug: "campina-da-lagoa", name: "Campina da Lagoa", region: "centro-ocidental" },
  { slug: "campina-do-simao", name: "Campina do Sim\u00e3o", region: "centro-sul" },
  { slug: "campo-bonito", name: "Campo Bonito", region: "oeste" },
  { slug: "campo-largo", name: "Campo Largo", region: "metropolitana" },
  { slug: "campo-magro", name: "Campo Magro", region: "metropolitana" },
  { slug: "campo-mourao", name: "Campo Mour\u00e3o", region: "centro-ocidental" },
  { slug: "campo-do-tenente", name: "Campo do Tenente", region: "metropolitana" },
  { slug: "candoi", name: "Cand\u00f3i", region: "centro-sul" },
  { slug: "cantagalo", name: "Cantagalo", region: "centro-sul" },
  { slug: "capanema", name: "Capanema", region: "sudoeste" },
  { slug: "capitao-leonidas-marques", name: "Capit\u00e3o Le\u00f4nidas Marques", region: "oeste" },
  { slug: "carambei", name: "Carambe\u00ed", region: "campos-gerais" },
  { slug: "carlopolis", name: "Carl\u00f3polis", region: "norte-pioneiro" },
  { slug: "cascavel", name: "Cascavel", region: "oeste" },
  { slug: "castro", name: "Castro", region: "campos-gerais" },
  { slug: "catanduvas", name: "Catanduvas", region: "oeste" },
  { slug: "centenario-do-sul", name: "Centen\u00e1rio do Sul", region: "norte-central" },
  { slug: "cerro-azul", name: "Cerro Azul", region: "metropolitana" },
  { slug: "chopinzinho", name: "Chopinzinho", region: "sudoeste" },
  { slug: "cianorte", name: "Cianorte", region: "noroeste" },
  { slug: "cidade-gaucha", name: "Cidade Ga\u00facha", region: "noroeste" },
  { slug: "clevelandia", name: "Clevel\u00e2ndia", region: "centro-sul" },
  { slug: "colombo", name: "Colombo", region: "metropolitana" },
  { slug: "colorado", name: "Colorado", region: "norte-central" },
  { slug: "congonhinhas", name: "Congonhinhas", region: "norte-pioneiro" },
  { slug: "conselheiro-mairinck", name: "Conselheiro Mairinck", region: "norte-pioneiro" },
  { slug: "contenda", name: "Contenda", region: "metropolitana" },
  { slug: "corbelia", name: "Corb\u00e9lia", region: "oeste" },
  { slug: "cornelio-procopio", name: "Corn\u00e9lio Proc\u00f3pio", region: "norte-pioneiro" },
  { slug: "coronel-domingos-soares", name: "Coronel Domingos Soares", region: "centro-sul" },
  { slug: "coronel-vivida", name: "Coronel Vivida", region: "sudoeste" },
  { slug: "corumbatai-do-sul", name: "Corumbata\u00ed do Sul", region: "centro-ocidental" },
  { slug: "cruz-machado", name: "Cruz Machado", region: "centro-sul" },
  { slug: "cruzeiro-do-iguacu", name: "Cruzeiro do Igua\u00e7u", region: "sudoeste" },
  { slug: "cruzeiro-do-oeste", name: "Cruzeiro do Oeste", region: "noroeste" },
  { slug: "cruzeiro-do-sul", name: "Cruzeiro do Sul", region: "noroeste" },
  { slug: "cruzmaltina", name: "Cruzmaltina", region: "norte-central" },
  { slug: "curitiba", name: "Curitiba", region: "metropolitana" },
  { slug: "curiuva", name: "Curi\u00fava", region: "norte-pioneiro" },
  { slug: "candido-de-abreu", name: "C\u00e2ndido de Abreu", region: "norte-central" },
  { slug: "ceu-azul", name: "C\u00e9u Azul", region: "oeste" },
  { slug: "diamante-d-oeste", name: "Diamante D'Oeste", region: "oeste" },
  { slug: "diamante-do-norte", name: "Diamante do Norte", region: "noroeste" },
  { slug: "diamante-do-sul", name: "Diamante do Sul", region: "oeste" },
  { slug: "dois-vizinhos", name: "Dois Vizinhos", region: "sudoeste" },
  { slug: "douradina", name: "Douradina", region: "noroeste" },
  { slug: "doutor-camargo", name: "Doutor Camargo", region: "norte-central" },
  { slug: "doutor-ulysses", name: "Doutor Ulysses", region: "metropolitana" },
  { slug: "engenheiro-beltrao", name: "Engenheiro Beltr\u00e3o", region: "centro-ocidental" },
  { slug: "entre-rios-do-oeste", name: "Entre Rios do Oeste", region: "oeste" },
  { slug: "eneas-marques", name: "En\u00e9as Marques", region: "sudoeste" },
  { slug: "esperanca-nova", name: "Esperan\u00e7a Nova", region: "noroeste" },
  { slug: "espigao-alto-do-iguacu", name: "Espig\u00e3o Alto do Igua\u00e7u", region: "centro-sul" },
  { slug: "farol", name: "Farol", region: "centro-ocidental" },
  { slug: "faxinal", name: "Faxinal", region: "norte-central" },
  { slug: "fazenda-rio-grande", name: "Fazenda Rio Grande", region: "metropolitana" },
  { slug: "fernandes-pinheiro", name: "Fernandes Pinheiro", region: "centro-sul" },
  { slug: "figueira", name: "Figueira", region: "norte-pioneiro" },
  { slug: "flor-da-serra-do-sul", name: "Flor da Serra do Sul", region: "sudoeste" },
  { slug: "florai", name: "Flora\u00ed", region: "norte-central" },
  { slug: "floresta", name: "Floresta", region: "norte-central" },
  { slug: "florestopolis", name: "Florest\u00f3polis", region: "norte-central" },
  { slug: "florida", name: "Fl\u00f3rida", region: "norte-central" },
  { slug: "formosa-do-oeste", name: "Formosa do Oeste", region: "oeste" },
  { slug: "foz-do-iguacu", name: "Foz do Igua\u00e7u", region: "oeste" },
  { slug: "foz-do-jordao", name: "Foz do Jord\u00e3o", region: "centro-sul" },
  { slug: "francisco-alves", name: "Francisco Alves", region: "noroeste" },
  { slug: "francisco-beltrao", name: "Francisco Beltr\u00e3o", region: "sudoeste" },
  { slug: "fenix", name: "F\u00eanix", region: "centro-ocidental" },
  { slug: "general-carneiro", name: "General Carneiro", region: "centro-sul" },
  { slug: "godoy-moreira", name: "Godoy Moreira", region: "norte-central" },
  { slug: "goioere", name: "Goioer\u00ea", region: "centro-ocidental" },
  { slug: "goioxim", name: "Goioxim", region: "centro-sul" },
  { slug: "grandes-rios", name: "Grandes Rios", region: "norte-central" },
  { slug: "guairaca", name: "Guaira\u00e7\u00e1", region: "noroeste" },
  { slug: "guamiranga", name: "Guamiranga", region: "centro-sul" },
  { slug: "guapirama", name: "Guapirama", region: "norte-pioneiro" },
  { slug: "guaporema", name: "Guaporema", region: "noroeste" },
  { slug: "guaraci", name: "Guaraci", region: "norte-central" },
  { slug: "guaraniacu", name: "Guarania\u00e7u", region: "oeste" },
  { slug: "guarapuava", name: "Guarapuava", region: "centro-sul" },
  { slug: "guaraquecaba", name: "Guaraque\u00e7aba", region: "litoral" },
  { slug: "guaratuba", name: "Guaratuba", region: "litoral" },
  { slug: "guaira", name: "Gua\u00edra", region: "oeste" },
  { slug: "honorio-serpa", name: "Hon\u00f3rio Serpa", region: "centro-sul" },
  { slug: "ibaiti", name: "Ibaiti", region: "norte-pioneiro" },
  { slug: "ibema", name: "Ibema", region: "oeste" },
  { slug: "ibipora", name: "Ibipor\u00e3", region: "norte-central" },
  { slug: "icaraima", name: "Icara\u00edma", region: "noroeste" },
  { slug: "iguaracu", name: "Iguara\u00e7u", region: "norte-central" },
  { slug: "iguatu", name: "Iguatu", region: "oeste" },
  { slug: "imbau", name: "Imba\u00fa", region: "campos-gerais" },
  { slug: "imbituva", name: "Imbituva", region: "centro-sul" },
  { slug: "inaja", name: "Inaj\u00e1", region: "noroeste" },
  { slug: "indianopolis", name: "Indian\u00f3polis", region: "noroeste" },
  { slug: "inacio-martins", name: "In\u00e1cio Martins", region: "centro-sul" },
  { slug: "ipiranga", name: "Ipiranga", region: "centro-sul" },
  { slug: "ipora", name: "Ipor\u00e3", region: "noroeste" },
  { slug: "iracema-do-oeste", name: "Iracema do Oeste", region: "oeste" },
  { slug: "irati", name: "Irati", region: "centro-sul" },
  { slug: "iretama", name: "Iretama", region: "centro-ocidental" },
  { slug: "itaguaje", name: "Itaguaj\u00e9", region: "norte-central" },
  { slug: "itaipulandia", name: "Itaipul\u00e2ndia", region: "oeste" },
  { slug: "itambaraca", name: "Itambarac\u00e1", region: "norte-pioneiro" },
  { slug: "itambe", name: "Itamb\u00e9", region: "norte-central" },
  { slug: "itapejara-d-oeste", name: "Itapejara d'Oeste", region: "sudoeste" },
  { slug: "itaperucu", name: "Itaperu\u00e7u", region: "metropolitana" },
  { slug: "itauna-do-sul", name: "Ita\u00fana do Sul", region: "noroeste" },
  { slug: "ivaipora", name: "Ivaipor\u00e3", region: "norte-central" },
  { slug: "ivatuba", name: "Ivatuba", region: "norte-central" },
  { slug: "ivate", name: "Ivat\u00e9", region: "noroeste" },
  { slug: "ivai", name: "Iva\u00ed", region: "centro-sul" },
  { slug: "jaboti", name: "Jaboti", region: "norte-pioneiro" },
  { slug: "jacarezinho", name: "Jacarezinho", region: "norte-pioneiro" },
  { slug: "jaguapita", name: "Jaguapit\u00e3", region: "norte-central" },
  { slug: "jaguariaiva", name: "Jaguaria\u00edva", region: "campos-gerais" },
  { slug: "jandaia-do-sul", name: "Jandaia do Sul", region: "norte-central" },
  { slug: "janiopolis", name: "Jani\u00f3polis", region: "centro-ocidental" },
  { slug: "japira", name: "Japira", region: "norte-pioneiro" },
  { slug: "japura", name: "Japur\u00e1", region: "noroeste" },
  { slug: "jardim-alegre", name: "Jardim Alegre", region: "norte-central" },
  { slug: "jardim-olinda", name: "Jardim Olinda", region: "noroeste" },
  { slug: "jataizinho", name: "Jataizinho", region: "norte-pioneiro" },
  { slug: "jesuitas", name: "Jesu\u00edtas", region: "oeste" },
  { slug: "joaquim-tavora", name: "Joaquim T\u00e1vora", region: "norte-pioneiro" },
  { slug: "jundiai-do-sul", name: "Jundia\u00ed do Sul", region: "norte-pioneiro" },
  { slug: "juranda", name: "Juranda", region: "centro-ocidental" },
  { slug: "jussara", name: "Jussara", region: "noroeste" },
  { slug: "kalore", name: "Kalor\u00e9", region: "norte-central" },
  { slug: "lapa", name: "Lapa", region: "metropolitana" },
  { slug: "laranjal", name: "Laranjal", region: "centro-sul" },
  { slug: "laranjeiras-do-sul", name: "Laranjeiras do Sul", region: "centro-sul" },
  { slug: "leopolis", name: "Le\u00f3polis", region: "norte-pioneiro" },
  { slug: "lidianopolis", name: "Lidian\u00f3polis", region: "norte-central" },
  { slug: "lindoeste", name: "Lindoeste", region: "oeste" },
  { slug: "loanda", name: "Loanda", region: "noroeste" },
  { slug: "lobato", name: "Lobato", region: "norte-central" },
  { slug: "londrina", name: "Londrina", region: "norte-central" },
  { slug: "luiziana", name: "Luiziana", region: "centro-ocidental" },
  { slug: "lunardelli", name: "Lunardelli", region: "norte-central" },
  { slug: "lupionopolis", name: "Lupion\u00f3polis", region: "norte-central" },
  { slug: "mallet", name: "Mallet", region: "centro-sul" },
  { slug: "mambore", name: "Mambor\u00ea", region: "centro-ocidental" },
  { slug: "mandaguari", name: "Mandaguari", region: "norte-central" },
  { slug: "mandaguacu", name: "Mandagua\u00e7u", region: "norte-central" },
  { slug: "mandirituba", name: "Mandirituba", region: "metropolitana" },
  { slug: "manfrinopolis", name: "Manfrin\u00f3polis", region: "sudoeste" },
  { slug: "mangueirinha", name: "Mangueirinha", region: "centro-sul" },
  { slug: "manoel-ribas", name: "Manoel Ribas", region: "norte-central" },
  { slug: "marechal-candido-rondon", name: "Marechal C\u00e2ndido Rondon", region: "oeste" },
  { slug: "maria-helena", name: "Maria Helena", region: "noroeste" },
  { slug: "marialva", name: "Marialva", region: "norte-central" },
  { slug: "marilena", name: "Marilena", region: "noroeste" },
  { slug: "mariluz", name: "Mariluz", region: "noroeste" },
  { slug: "marilandia-do-sul", name: "Maril\u00e2ndia do Sul", region: "norte-central" },
  { slug: "maringa", name: "Maring\u00e1", region: "norte-central" },
  { slug: "maripa", name: "Marip\u00e1", region: "oeste" },
  { slug: "mariopolis", name: "Mari\u00f3polis", region: "sudoeste" },
  { slug: "marmeleiro", name: "Marmeleiro", region: "sudoeste" },
  { slug: "marquinho", name: "Marquinho", region: "centro-sul" },
  { slug: "marumbi", name: "Marumbi", region: "norte-central" },
  { slug: "matelandia", name: "Matel\u00e2ndia", region: "oeste" },
  { slug: "matinhos", name: "Matinhos", region: "litoral" },
  { slug: "mato-rico", name: "Mato Rico", region: "centro-sul" },
  { slug: "maua-da-serra", name: "Mau\u00e1 da Serra", region: "norte-central" },
  { slug: "medianeira", name: "Medianeira", region: "oeste" },
  { slug: "mercedes", name: "Mercedes", region: "oeste" },
  { slug: "mirador", name: "Mirador", region: "noroeste" },
  { slug: "miraselva", name: "Miraselva", region: "norte-central" },
  { slug: "missal", name: "Missal", region: "oeste" },
  { slug: "moreira-sales", name: "Moreira Sales", region: "centro-ocidental" },
  { slug: "morretes", name: "Morretes", region: "litoral" },
  { slug: "munhoz-de-melo", name: "Munhoz de Melo", region: "norte-central" },
  { slug: "nossa-senhora-das-gracas", name: "Nossa Senhora das Gra\u00e7as", region: "norte-central" },
  { slug: "nova-alianca-do-ivai", name: "Nova Alian\u00e7a do Iva\u00ed", region: "noroeste" },
  { slug: "nova-america-da-colina", name: "Nova Am\u00e9rica da Colina", region: "norte-pioneiro" },
  { slug: "nova-aurora", name: "Nova Aurora", region: "oeste" },
  { slug: "nova-cantu", name: "Nova Cantu", region: "centro-ocidental" },
  { slug: "nova-esperanca", name: "Nova Esperan\u00e7a", region: "norte-central" },
  { slug: "nova-esperanca-do-sudoeste", name: "Nova Esperan\u00e7a do Sudoeste", region: "sudoeste" },
  { slug: "nova-fatima", name: "Nova F\u00e1tima", region: "norte-pioneiro" },
  { slug: "nova-laranjeiras", name: "Nova Laranjeiras", region: "centro-sul" },
  { slug: "nova-londrina", name: "Nova Londrina", region: "noroeste" },
  { slug: "nova-olimpia", name: "Nova Ol\u00edmpia", region: "noroeste" },
  { slug: "nova-prata-do-iguacu", name: "Nova Prata do Igua\u00e7u", region: "sudoeste" },
  { slug: "nova-santa-barbara", name: "Nova Santa B\u00e1rbara", region: "norte-pioneiro" },
  { slug: "nova-santa-rosa", name: "Nova Santa Rosa", region: "oeste" },
  { slug: "nova-tebas", name: "Nova Tebas", region: "norte-central" },
  { slug: "novo-itacolomi", name: "Novo Itacolomi", region: "norte-central" },
  { slug: "ortigueira", name: "Ortigueira", region: "campos-gerais" },
  { slug: "ourizona", name: "Ourizona", region: "norte-central" },
  { slug: "ouro-verde-do-oeste", name: "Ouro Verde do Oeste", region: "oeste" },
  { slug: "paicandu", name: "Pai\u00e7andu", region: "norte-central" },
  { slug: "palmas", name: "Palmas", region: "centro-sul" },
  { slug: "palmeira", name: "Palmeira", region: "campos-gerais" },
  { slug: "palmital", name: "Palmital", region: "centro-sul" },
  { slug: "palotina", name: "Palotina", region: "oeste" },
  { slug: "paranacity", name: "Paranacity", region: "noroeste" },
  { slug: "paranagua", name: "Paranagu\u00e1", region: "litoral" },
  { slug: "paranapoema", name: "Paranapoema", region: "noroeste" },
  { slug: "paranavai", name: "Paranava\u00ed", region: "noroeste" },
  { slug: "paraiso-do-norte", name: "Para\u00edso do Norte", region: "noroeste" },
  { slug: "pato-bragado", name: "Pato Bragado", region: "oeste" },
  { slug: "pato-branco", name: "Pato Branco", region: "sudoeste" },
  { slug: "paula-freitas", name: "Paula Freitas", region: "centro-sul" },
  { slug: "paulo-frontin", name: "Paulo Frontin", region: "centro-sul" },
  { slug: "peabiru", name: "Peabiru", region: "centro-ocidental" },
  { slug: "perobal", name: "Perobal", region: "noroeste" },
  { slug: "pinhais", name: "Pinhais", region: "metropolitana" },
  { slug: "pinhal-de-sao-bento", name: "Pinhal de S\u00e3o Bento", region: "sudoeste" },
  { slug: "pinhalao", name: "Pinhal\u00e3o", region: "norte-pioneiro" },
  { slug: "pinhao", name: "Pinh\u00e3o", region: "centro-sul" },
  { slug: "piraquara", name: "Piraquara", region: "metropolitana" },
  { slug: "pirai-do-sul", name: "Pira\u00ed do Sul", region: "campos-gerais" },
  { slug: "pitanga", name: "Pitanga", region: "centro-sul" },
  { slug: "pitangueiras", name: "Pitangueiras", region: "norte-central" },
  { slug: "pien", name: "Pi\u00ean", region: "metropolitana" },
  { slug: "planaltina-do-parana", name: "Planaltina do Paran\u00e1", region: "noroeste" },
  { slug: "planalto", name: "Planalto", region: "sudoeste" },
  { slug: "ponta-grossa", name: "Ponta Grossa", region: "campos-gerais" },
  { slug: "pontal-do-parana", name: "Pontal do Paran\u00e1", region: "litoral" },
  { slug: "porecatu", name: "Porecatu", region: "norte-central" },
  { slug: "porto-amazonas", name: "Porto Amazonas", region: "metropolitana" },
  { slug: "porto-barreiro", name: "Porto Barreiro", region: "centro-sul" },
  { slug: "porto-rico", name: "Porto Rico", region: "noroeste" },
  { slug: "porto-vitoria", name: "Porto Vit\u00f3ria", region: "centro-sul" },
  { slug: "prado-ferreira", name: "Prado Ferreira", region: "norte-central" },
  { slug: "pranchita", name: "Pranchita", region: "sudoeste" },
  { slug: "presidente-castelo-branco", name: "Presidente Castelo Branco", region: "norte-central" },
  { slug: "primeiro-de-maio", name: "Primeiro de Maio", region: "norte-central" },
  { slug: "prudentopolis", name: "Prudent\u00f3polis", region: "centro-sul" },
  { slug: "perola", name: "P\u00e9rola", region: "noroeste" },
  { slug: "perola-d-oeste", name: "P\u00e9rola d'Oeste", region: "sudoeste" },
  { slug: "quarto-centenario", name: "Quarto Centen\u00e1rio", region: "centro-ocidental" },
  { slug: "quatigua", name: "Quatigu\u00e1", region: "norte-pioneiro" },
  { slug: "quatro-barras", name: "Quatro Barras", region: "metropolitana" },
  { slug: "quatro-pontes", name: "Quatro Pontes", region: "oeste" },
  { slug: "quedas-do-iguacu", name: "Quedas do Igua\u00e7u", region: "centro-sul" },
  { slug: "querencia-do-norte", name: "Quer\u00eancia do Norte", region: "noroeste" },
  { slug: "quinta-do-sol", name: "Quinta do Sol", region: "centro-ocidental" },
  { slug: "quitandinha", name: "Quitandinha", region: "metropolitana" },
  { slug: "ramilandia", name: "Ramil\u00e2ndia", region: "oeste" },
  { slug: "rancho-alegre", name: "Rancho Alegre", region: "norte-pioneiro" },
  { slug: "rancho-alegre-d-oeste", name: "Rancho Alegre D'Oeste", region: "centro-ocidental" },
  { slug: "realeza", name: "Realeza", region: "sudoeste" },
  { slug: "reboucas", name: "Rebou\u00e7as", region: "centro-sul" },
  { slug: "renascenca", name: "Renascen\u00e7a", region: "sudoeste" },
  { slug: "reserva", name: "Reserva", region: "campos-gerais" },
  { slug: "reserva-do-iguacu", name: "Reserva do Igua\u00e7u", region: "centro-sul" },
  { slug: "ribeirao-claro", name: "Ribeir\u00e3o Claro", region: "norte-pioneiro" },
  { slug: "ribeirao-do-pinhal", name: "Ribeir\u00e3o do Pinhal", region: "norte-pioneiro" },
  { slug: "rio-azul", name: "Rio Azul", region: "centro-sul" },
  { slug: "rio-bom", name: "Rio Bom", region: "norte-central" },
  { slug: "rio-bonito-do-iguacu", name: "Rio Bonito do Igua\u00e7u", region: "centro-sul" },
  { slug: "rio-branco-do-ivai", name: "Rio Branco do Iva\u00ed", region: "norte-central" },
  { slug: "rio-branco-do-sul", name: "Rio Branco do Sul", region: "metropolitana" },
  { slug: "rio-negro", name: "Rio Negro", region: "metropolitana" },
  { slug: "rolandia", name: "Rol\u00e2ndia", region: "norte-central" },
  { slug: "roncador", name: "Roncador", region: "centro-ocidental" },
  { slug: "rondon", name: "Rondon", region: "noroeste" },
  { slug: "rosario-do-ivai", name: "Ros\u00e1rio do Iva\u00ed", region: "norte-central" },
  { slug: "sabaudia", name: "Sab\u00e1udia", region: "norte-central" },
  { slug: "salgado-filho", name: "Salgado Filho", region: "sudoeste" },
  { slug: "salto-do-itarare", name: "Salto do Itarar\u00e9", region: "norte-pioneiro" },
  { slug: "salto-do-lontra", name: "Salto do Lontra", region: "sudoeste" },
  { slug: "santa-amelia", name: "Santa Am\u00e9lia", region: "norte-pioneiro" },
  { slug: "santa-cecilia-do-pavao", name: "Santa Cec\u00edlia do Pav\u00e3o", region: "norte-pioneiro" },
  { slug: "santa-cruz-de-monte-castelo", name: "Santa Cruz de Monte Castelo", region: "noroeste" },
  { slug: "santa-fe", name: "Santa F\u00e9", region: "norte-central" },
  { slug: "santa-helena", name: "Santa Helena", region: "oeste" },
  { slug: "santa-ines", name: "Santa In\u00eas", region: "norte-central" },
  { slug: "santa-isabel-do-ivai", name: "Santa Isabel do Iva\u00ed", region: "noroeste" },
  { slug: "santa-izabel-do-oeste", name: "Santa Izabel do Oeste", region: "sudoeste" },
  { slug: "santa-lucia", name: "Santa L\u00facia", region: "oeste" },
  { slug: "santa-maria-do-oeste", name: "Santa Maria do Oeste", region: "centro-sul" },
  { slug: "santa-mariana", name: "Santa Mariana", region: "norte-pioneiro" },
  { slug: "santa-monica", name: "Santa M\u00f4nica", region: "noroeste" },
  { slug: "santa-tereza-do-oeste", name: "Santa Tereza do Oeste", region: "oeste" },
  { slug: "santa-terezinha-de-itaipu", name: "Santa Terezinha de Itaipu", region: "oeste" },
  { slug: "santana-do-itarare", name: "Santana do Itarar\u00e9", region: "norte-pioneiro" },
  { slug: "santo-antonio-da-platina", name: "Santo Ant\u00f4nio da Platina", region: "norte-pioneiro" },
  { slug: "santo-antonio-do-caiua", name: "Santo Ant\u00f4nio do Caiu\u00e1", region: "noroeste" },
  { slug: "santo-antonio-do-paraiso", name: "Santo Ant\u00f4nio do Para\u00edso", region: "norte-pioneiro" },
  { slug: "santo-antonio-do-sudoeste", name: "Santo Ant\u00f4nio do Sudoeste", region: "sudoeste" },
  { slug: "santo-inacio", name: "Santo In\u00e1cio", region: "norte-central" },
  { slug: "sapopema", name: "Sapopema", region: "norte-pioneiro" },
  { slug: "sarandi", name: "Sarandi", region: "norte-central" },
  { slug: "saudade-do-iguacu", name: "Saudade do Igua\u00e7u", region: "sudoeste" },
  { slug: "senges", name: "Seng\u00e9s", region: "campos-gerais" },
  { slug: "serranopolis-do-iguacu", name: "Serran\u00f3polis do Igua\u00e7u", region: "oeste" },
  { slug: "sertaneja", name: "Sertaneja", region: "norte-pioneiro" },
  { slug: "sertanopolis", name: "Sertan\u00f3polis", region: "norte-central" },
  { slug: "siqueira-campos", name: "Siqueira Campos", region: "norte-pioneiro" },
  { slug: "sulina", name: "Sulina", region: "sudoeste" },
  { slug: "sao-carlos-do-ivai", name: "S\u00e3o Carlos do Iva\u00ed", region: "noroeste" },
  { slug: "sao-jeronimo-da-serra", name: "S\u00e3o Jer\u00f4nimo da Serra", region: "norte-pioneiro" },
  { slug: "sao-jorge-d-oeste", name: "S\u00e3o Jorge d'Oeste", region: "sudoeste" },
  { slug: "sao-jorge-do-ivai", name: "S\u00e3o Jorge do Iva\u00ed", region: "norte-central" },
  { slug: "sao-jorge-do-patrocinio", name: "S\u00e3o Jorge do Patroc\u00ednio", region: "noroeste" },
  { slug: "sao-jose-da-boa-vista", name: "S\u00e3o Jos\u00e9 da Boa Vista", region: "norte-pioneiro" },
  { slug: "sao-jose-das-palmeiras", name: "S\u00e3o Jos\u00e9 das Palmeiras", region: "oeste" },
  { slug: "sao-jose-dos-pinhais", name: "S\u00e3o Jos\u00e9 dos Pinhais", region: "metropolitana" },
  { slug: "sao-joao", name: "S\u00e3o Jo\u00e3o", region: "sudoeste" },
  { slug: "sao-joao-do-caiua", name: "S\u00e3o Jo\u00e3o do Caiu\u00e1", region: "noroeste" },
  { slug: "sao-joao-do-ivai", name: "S\u00e3o Jo\u00e3o do Iva\u00ed", region: "norte-central" },
  { slug: "sao-joao-do-triunfo", name: "S\u00e3o Jo\u00e3o do Triunfo", region: "centro-sul" },
  { slug: "sao-manoel-do-parana", name: "S\u00e3o Manoel do Paran\u00e1", region: "noroeste" },
  { slug: "sao-mateus-do-sul", name: "S\u00e3o Mateus do Sul", region: "centro-sul" },
  { slug: "sao-miguel-do-iguacu", name: "S\u00e3o Miguel do Igua\u00e7u", region: "oeste" },
  { slug: "sao-pedro-do-iguacu", name: "S\u00e3o Pedro do Igua\u00e7u", region: "oeste" },
  { slug: "sao-pedro-do-ivai", name: "S\u00e3o Pedro do Iva\u00ed", region: "norte-central" },
  { slug: "sao-pedro-do-parana", name: "S\u00e3o Pedro do Paran\u00e1", region: "noroeste" },
  { slug: "sao-sebastiao-da-amoreira", name: "S\u00e3o Sebasti\u00e3o da Amoreira", region: "norte-pioneiro" },
  { slug: "sao-tome", name: "S\u00e3o Tom\u00e9", region: "noroeste" },
  { slug: "tamarana", name: "Tamarana", region: "norte-central" },
  { slug: "tamboara", name: "Tamboara", region: "noroeste" },
  { slug: "tapejara", name: "Tapejara", region: "noroeste" },
  { slug: "tapira", name: "Tapira", region: "noroeste" },
  { slug: "teixeira-soares", name: "Teixeira Soares", region: "centro-sul" },
  { slug: "telemaco-borba", name: "Tel\u00eamaco Borba", region: "campos-gerais" },
  { slug: "terra-boa", name: "Terra Boa", region: "centro-ocidental" },
  { slug: "terra-rica", name: "Terra Rica", region: "noroeste" },
  { slug: "terra-roxa", name: "Terra Roxa", region: "oeste" },
  { slug: "tibagi", name: "Tibagi", region: "campos-gerais" },
  { slug: "tijucas-do-sul", name: "Tijucas do Sul", region: "metropolitana" },
  { slug: "toledo", name: "Toledo", region: "oeste" },
  { slug: "tomazina", name: "Tomazina", region: "norte-pioneiro" },
  { slug: "tres-barras-do-parana", name: "Tr\u00eas Barras do Paran\u00e1", region: "oeste" },
  { slug: "tunas-do-parana", name: "Tunas do Paran\u00e1", region: "metropolitana" },
  { slug: "tuneiras-do-oeste", name: "Tuneiras do Oeste", region: "noroeste" },
  { slug: "tupassi", name: "Tup\u00e3ssi", region: "oeste" },
  { slug: "turvo", name: "Turvo", region: "centro-sul" },
  { slug: "ubirata", name: "Ubirat\u00e3", region: "centro-ocidental" },
  { slug: "umuarama", name: "Umuarama", region: "noroeste" },
  { slug: "uniflor", name: "Uniflor", region: "norte-central" },
  { slug: "uniao-da-vitoria", name: "Uni\u00e3o da Vit\u00f3ria", region: "centro-sul" },
  { slug: "urai", name: "Ura\u00ed", region: "norte-pioneiro" },
  { slug: "ventania", name: "Ventania", region: "campos-gerais" },
  { slug: "vera-cruz-do-oeste", name: "Vera Cruz do Oeste", region: "oeste" },
  { slug: "vere", name: "Ver\u00ea", region: "sudoeste" },
  { slug: "virmond", name: "Virmond", region: "centro-sul" },
  { slug: "vitorino", name: "Vitorino", region: "sudoeste" },
  { slug: "wenceslau-braz", name: "Wenceslau Braz", region: "norte-pioneiro" },
  { slug: "xambre", name: "Xambr\u00ea", region: "noroeste" },
  { slug: "angulo", name: "\u00c2ngulo", region: "norte-central" },
] as const;

function normalize(v: string): string {
  return v
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

function toSlug(v: string): string {
  return normalize(v).replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const BY_SLUG: Map<string, Municipio> = new Map(
  PARANA_MUNICIPIOS.map((m) => [m.slug, m as Municipio]),
);
const BY_NAME_NORM: Map<string, Municipio> = new Map(
  PARANA_MUNICIPIOS.map((m) => [normalize(m.name), m as Municipio]),
);

/** Retorna o município pelo slug canônico, ou null. */
export function findMunicipioBySlug(slug: string): Municipio | null {
  return BY_SLUG.get(slug) ?? null;
}

/** Aceita nome livre ("Foz do Iguaçu", "foz-do-iguacu", " FOZ  DO IGUAÇU ")
 *  e retorna o município canônico, ou null. */
export function findMunicipio(input: string): Municipio | null {
  const raw = input.trim();
  if (!raw) return null;
  const slug = toSlug(raw);
  const bySlug = BY_SLUG.get(slug);
  if (bySlug) return bySlug;
  const norm = normalize(raw);
  return BY_NAME_NORM.get(norm) ?? null;
}

/** Faz o parse de "Cascavel, Toledo; Medianeira\nFoz do Iguaçu".
 *  Retorna slugs reconhecidos e a lista dos termos que não bateram. */
export function parseCityList(input: string): { found: Municipio[]; unknown: string[] } {
  const parts = input
    .split(/[,;\n]+/)
    .map((p) => p.trim())
    .filter(Boolean);
  const found: Municipio[] = [];
  const seen = new Set<string>();
  const unknown: string[] = [];
  for (const p of parts) {
    const m = findMunicipio(p);
    if (m && !seen.has(m.slug)) {
      seen.add(m.slug);
      found.push(m);
    } else if (!m) {
      unknown.push(p);
    }
  }
  return { found, unknown };
}

/** Sugestões (top-N) para autocomplete. Filtra por prefixo normalizado do nome. */
export function suggestMunicipios(query: string, limit = 8): Municipio[] {
  const q = normalize(query);
  if (!q) return [];
  const out: Municipio[] = [];
  for (const m of PARANA_MUNICIPIOS as unknown as Municipio[]) {
    if (normalize(m.name).startsWith(q)) {
      out.push(m);
      if (out.length >= limit) break;
    }
  }
  if (out.length < limit) {
    for (const m of PARANA_MUNICIPIOS as unknown as Municipio[]) {
      if (out.includes(m)) continue;
      if (normalize(m.name).includes(q)) {
        out.push(m);
        if (out.length >= limit) break;
      }
    }
  }
  return out;
}

/** Cidades pertencentes a uma região editorial. */
export function citiesInRegion(regionSlug: string): Municipio[] {
  return (PARANA_MUNICIPIOS as unknown as Municipio[]).filter((m) => m.region === regionSlug);
}
