/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PoliticaEditorialRouteImport } from './routes/politica-editorial'
import { Route as CorrecoesRouteImport } from './routes/correcoes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RegionRouteImport } from './routes/$region'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegionIndexRouteImport } from './routes/$region.index'
import { Route as VitrineTokenRouteImport } from './routes/vitrine.$token'
import { Route as VitrinePessoalNovoRouteImport } from './routes/vitrine-pessoal.novo'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as PublieditorialTokenRouteImport } from './routes/publieditorial.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as EditoriaCategoriaRouteImport } from './routes/editoria.$categoria'
import { Route as AutorSlugRouteImport } from './routes/autor.$slug'
import { Route as AdminVitrinePessoalRouteImport } from './routes/admin.vitrine-pessoal'
import { Route as AdminSenhaRouteImport } from './routes/admin.senha'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminRegioesRouteImport } from './routes/admin.regioes'
import { Route as AdminPedidosChatRouteImport } from './routes/admin.pedidos-chat'
import { Route as AdminPainelRouteImport } from './routes/admin.painel'
import { Route as AdminMemoriaEditorialRouteImport } from './routes/admin.memoria-editorial'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFontesRouteImport } from './routes/admin.fontes'
import { Route as AdminClustersRouteImport } from './routes/admin.clusters'
import { Route as AdminAnunciosRouteImport } from './routes/admin.anuncios'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAgentesRouteImport } from './routes/admin.agentes'
import { Route as RegionClassificadosRouteImport } from './routes/$region.classificados'
import { Route as RegionSlugRouteImport } from './routes/$region.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicSitemapNewsDotxmlRouteImport } from './routes/api/public/sitemap-news[.]xml'
import { Route as ApiPublicRssDotxmlRouteImport } from './routes/api/public/rss[.]xml'
import { Route as ApiPublicLlmsDottxtRouteImport } from './routes/api/public/llms[.]txt'
import { Route as ApiPublicLlmsFullDottxtRouteImport } from './routes/api/public/llms-full[.]txt'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as RegionEditoriaCategoriaRouteImport } from './routes/$region.editoria.$categoria'
import { Route as RegionCidadeCidadeRouteImport } from './routes/$region.cidade.$cidade'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicIndexnowKeyRouteImport } from './routes/api/public/indexnow.$key'
import { Route as ApiPublicHooksIndexnowPingRouteImport } from './routes/api/public/hooks.indexnow-ping'
import { Route as ApiPublicRssRegiaoRegionRouteImport } from './routes/api/public/rss.regiao.$region'
import { Route as ApiPublicRssCategoriaSlugRouteImport } from './routes/api/public/rss.categoria.$slug'
import { Route as ApiPublicRssCidadeRegionCidadeRouteImport } from './routes/api/public/rss.cidade.$region.$cidade'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaEditorialRoute = PoliticaEditorialRouteImport.update({
  id: '/politica-editorial',
  path: '/politica-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrecoesRoute = CorrecoesRouteImport.update({
  id: '/correcoes',
  path: '/correcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegionIndexRoute = RegionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionRoute,
} as any)
const VitrineTokenRoute = VitrineTokenRouteImport.update({
  id: '/vitrine/$token',
  path: '/vitrine/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrinePessoalNovoRoute = VitrinePessoalNovoRouteImport.update({
  id: '/vitrine-pessoal/novo',
  path: '/vitrine-pessoal/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PublieditorialTokenRoute = PublieditorialTokenRouteImport.update({
  id: '/publieditorial/$token',
  path: '/publieditorial/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const EditoriaCategoriaRoute = EditoriaCategoriaRouteImport.update({
  id: '/editoria/$categoria',
  path: '/editoria/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorSlugRoute = AutorSlugRouteImport.update({
  id: '/autor/$slug',
  path: '/autor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVitrinePessoalRoute = AdminVitrinePessoalRouteImport.update({
  id: '/vitrine-pessoal',
  path: '/vitrine-pessoal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSenhaRoute = AdminSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegioesRoute = AdminRegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosChatRoute = AdminPedidosChatRouteImport.update({
  id: '/pedidos-chat',
  path: '/pedidos-chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPainelRoute = AdminPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMemoriaEditorialRoute = AdminMemoriaEditorialRouteImport.update({
  id: '/memoria-editorial',
  path: '/memoria-editorial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFontesRoute = AdminFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClustersRoute = AdminClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentesRoute = AdminAgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => AdminRoute,
} as any)
const RegionClassificadosRoute = RegionClassificadosRouteImport.update({
  id: '/classificados',
  path: '/classificados',
  getParentRoute: () => RegionRoute,
} as any)
const RegionSlugRoute = RegionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapNewsDotxmlRoute =
  ApiPublicSitemapNewsDotxmlRouteImport.update({
    id: '/api/public/sitemap-news.xml',
    path: '/api/public/sitemap-news.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssDotxmlRoute = ApiPublicRssDotxmlRouteImport.update({
  id: '/api/public/rss.xml',
  path: '/api/public/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLlmsDottxtRoute = ApiPublicLlmsDottxtRouteImport.update({
  id: '/api/public/llms.txt',
  path: '/api/public/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLlmsFullDottxtRoute = ApiPublicLlmsFullDottxtRouteImport.update({
  id: '/api/public/llms-full.txt',
  path: '/api/public/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionEditoriaCategoriaRoute = RegionEditoriaCategoriaRouteImport.update({
  id: '/editoria/$categoria',
  path: '/editoria/$categoria',
  getParentRoute: () => RegionRoute,
} as any)
const RegionCidadeCidadeRoute = RegionCidadeCidadeRouteImport.update({
  id: '/cidade/$cidade',
  path: '/cidade/$cidade',
  getParentRoute: () => RegionRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIndexnowKeyRoute = ApiPublicIndexnowKeyRouteImport.update({
  id: '/api/public/indexnow/$key',
  path: '/api/public/indexnow/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIndexnowPingRoute =
  ApiPublicHooksIndexnowPingRouteImport.update({
    id: '/api/public/hooks/indexnow-ping',
    path: '/api/public/hooks/indexnow-ping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssRegiaoRegionRoute =
  ApiPublicRssRegiaoRegionRouteImport.update({
    id: '/api/public/rss/regiao/$region',
    path: '/api/public/rss/regiao/$region',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssCategoriaSlugRoute =
  ApiPublicRssCategoriaSlugRouteImport.update({
    id: '/api/public/rss/categoria/$slug',
    path: '/api/public/rss/categoria/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssCidadeRegionCidadeRoute =
  ApiPublicRssCidadeRegionCidadeRouteImport.update({
    id: '/api/public/rss/cidade/$region/$cidade',
    path: '/api/public/rss/cidade/$region/$cidade',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/correcoes': typeof CorrecoesRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/agentes': typeof AdminAgentesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/memoria-editorial': typeof AdminMemoriaEditorialRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/pedidos-chat': typeof AdminPedidosChatRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/admin/vitrine-pessoal': typeof AdminVitrinePessoalRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/editoria/$categoria': typeof EditoriaCategoriaRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/publieditorial/$token': typeof PublieditorialTokenRoute
  '/r/$id': typeof RIdRoute
  '/vitrine-pessoal/novo': typeof VitrinePessoalNovoRoute
  '/vitrine/$token': typeof VitrineTokenRoute
  '/$region/': typeof RegionIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$region/cidade/$cidade': typeof RegionCidadeCidadeRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/llms-full.txt': typeof ApiPublicLlmsFullDottxtRoute
  '/api/public/llms.txt': typeof ApiPublicLlmsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap-news.xml': typeof ApiPublicSitemapNewsDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/indexnow-ping': typeof ApiPublicHooksIndexnowPingRoute
  '/api/public/indexnow/$key': typeof ApiPublicIndexnowKeyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/rss/categoria/$slug': typeof ApiPublicRssCategoriaSlugRoute
  '/api/public/rss/regiao/$region': typeof ApiPublicRssRegiaoRegionRoute
  '/api/public/rss/cidade/$region/$cidade': typeof ApiPublicRssCidadeRegionCidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/correcoes': typeof CorrecoesRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/agentes': typeof AdminAgentesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/memoria-editorial': typeof AdminMemoriaEditorialRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/pedidos-chat': typeof AdminPedidosChatRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/admin/vitrine-pessoal': typeof AdminVitrinePessoalRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/editoria/$categoria': typeof EditoriaCategoriaRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/publieditorial/$token': typeof PublieditorialTokenRoute
  '/r/$id': typeof RIdRoute
  '/vitrine-pessoal/novo': typeof VitrinePessoalNovoRoute
  '/vitrine/$token': typeof VitrineTokenRoute
  '/$region': typeof RegionIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$region/cidade/$cidade': typeof RegionCidadeCidadeRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/llms-full.txt': typeof ApiPublicLlmsFullDottxtRoute
  '/api/public/llms.txt': typeof ApiPublicLlmsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap-news.xml': typeof ApiPublicSitemapNewsDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/indexnow-ping': typeof ApiPublicHooksIndexnowPingRoute
  '/api/public/indexnow/$key': typeof ApiPublicIndexnowKeyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/rss/categoria/$slug': typeof ApiPublicRssCategoriaSlugRoute
  '/api/public/rss/regiao/$region': typeof ApiPublicRssRegiaoRegionRoute
  '/api/public/rss/cidade/$region/$cidade': typeof ApiPublicRssCidadeRegionCidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/correcoes': typeof CorrecoesRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/agentes': typeof AdminAgentesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/memoria-editorial': typeof AdminMemoriaEditorialRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/pedidos-chat': typeof AdminPedidosChatRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/admin/vitrine-pessoal': typeof AdminVitrinePessoalRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/editoria/$categoria': typeof EditoriaCategoriaRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/publieditorial/$token': typeof PublieditorialTokenRoute
  '/r/$id': typeof RIdRoute
  '/vitrine-pessoal/novo': typeof VitrinePessoalNovoRoute
  '/vitrine/$token': typeof VitrineTokenRoute
  '/$region/': typeof RegionIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$region/cidade/$cidade': typeof RegionCidadeCidadeRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/llms-full.txt': typeof ApiPublicLlmsFullDottxtRoute
  '/api/public/llms.txt': typeof ApiPublicLlmsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap-news.xml': typeof ApiPublicSitemapNewsDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/indexnow-ping': typeof ApiPublicHooksIndexnowPingRoute
  '/api/public/indexnow/$key': typeof ApiPublicIndexnowKeyRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/rss/categoria/$slug': typeof ApiPublicRssCategoriaSlugRoute
  '/api/public/rss/regiao/$region': typeof ApiPublicRssRegiaoRegionRoute
  '/api/public/rss/cidade/$region/$cidade': typeof ApiPublicRssCidadeRegionCidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region'
    | '/admin'
    | '/contato'
    | '/correcoes'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/unsubscribe'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/agentes'
    | '/admin/analytics'
    | '/admin/anuncios'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/memoria-editorial'
    | '/admin/painel'
    | '/admin/pedidos-chat'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/admin/vitrine-pessoal'
    | '/autor/$slug'
    | '/editoria/$categoria'
    | '/email/unsubscribe'
    | '/publieditorial/$token'
    | '/r/$id'
    | '/vitrine-pessoal/novo'
    | '/vitrine/$token'
    | '/$region/'
    | '/admin/'
    | '/$region/cidade/$cidade'
    | '/$region/editoria/$categoria'
    | '/api/public/contact'
    | '/api/public/llms-full.txt'
    | '/api/public/llms.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap-news.xml'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/indexnow-ping'
    | '/api/public/indexnow/$key'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/rss/categoria/$slug'
    | '/api/public/rss/regiao/$region'
    | '/api/public/rss/cidade/$region/$cidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/correcoes'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/unsubscribe'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/agentes'
    | '/admin/analytics'
    | '/admin/anuncios'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/memoria-editorial'
    | '/admin/painel'
    | '/admin/pedidos-chat'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/admin/vitrine-pessoal'
    | '/autor/$slug'
    | '/editoria/$categoria'
    | '/email/unsubscribe'
    | '/publieditorial/$token'
    | '/r/$id'
    | '/vitrine-pessoal/novo'
    | '/vitrine/$token'
    | '/$region'
    | '/admin'
    | '/$region/cidade/$cidade'
    | '/$region/editoria/$categoria'
    | '/api/public/contact'
    | '/api/public/llms-full.txt'
    | '/api/public/llms.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap-news.xml'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/indexnow-ping'
    | '/api/public/indexnow/$key'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/rss/categoria/$slug'
    | '/api/public/rss/regiao/$region'
    | '/api/public/rss/cidade/$region/$cidade'
  id:
    | '__root__'
    | '/'
    | '/$region'
    | '/admin'
    | '/contato'
    | '/correcoes'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/unsubscribe'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/agentes'
    | '/admin/analytics'
    | '/admin/anuncios'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/memoria-editorial'
    | '/admin/painel'
    | '/admin/pedidos-chat'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/admin/vitrine-pessoal'
    | '/autor/$slug'
    | '/editoria/$categoria'
    | '/email/unsubscribe'
    | '/publieditorial/$token'
    | '/r/$id'
    | '/vitrine-pessoal/novo'
    | '/vitrine/$token'
    | '/$region/'
    | '/admin/'
    | '/$region/cidade/$cidade'
    | '/$region/editoria/$categoria'
    | '/api/public/contact'
    | '/api/public/llms-full.txt'
    | '/api/public/llms.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap-news.xml'
    | '/api/public/sitemap.xml'
    | '/lovable/email/suppression'
    | '/api/public/hooks/indexnow-ping'
    | '/api/public/indexnow/$key'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/rss/categoria/$slug'
    | '/api/public/rss/regiao/$region'
    | '/api/public/rss/cidade/$region/$cidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionRoute: typeof RegionRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CorrecoesRoute: typeof CorrecoesRoute
  PoliticaEditorialRoute: typeof PoliticaEditorialRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WhatsappRoute: typeof WhatsappRoute
  AutorSlugRoute: typeof AutorSlugRoute
  EditoriaCategoriaRoute: typeof EditoriaCategoriaRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PublieditorialTokenRoute: typeof PublieditorialTokenRoute
  RIdRoute: typeof RIdRoute
  VitrinePessoalNovoRoute: typeof VitrinePessoalNovoRoute
  VitrineTokenRoute: typeof VitrineTokenRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicLlmsFullDottxtRoute: typeof ApiPublicLlmsFullDottxtRoute
  ApiPublicLlmsDottxtRoute: typeof ApiPublicLlmsDottxtRoute
  ApiPublicRssDotxmlRoute: typeof ApiPublicRssDotxmlRoute
  ApiPublicSitemapNewsDotxmlRoute: typeof ApiPublicSitemapNewsDotxmlRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksIndexnowPingRoute: typeof ApiPublicHooksIndexnowPingRoute
  ApiPublicIndexnowKeyRoute: typeof ApiPublicIndexnowKeyRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicRssCategoriaSlugRoute: typeof ApiPublicRssCategoriaSlugRoute
  ApiPublicRssRegiaoRegionRoute: typeof ApiPublicRssRegiaoRegionRoute
  ApiPublicRssCidadeRegionCidadeRoute: typeof ApiPublicRssCidadeRegionCidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-editorial': {
      id: '/politica-editorial'
      path: '/politica-editorial'
      fullPath: '/politica-editorial'
      preLoaderRoute: typeof PoliticaEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correcoes': {
      id: '/correcoes'
      path: '/correcoes'
      fullPath: '/correcoes'
      preLoaderRoute: typeof CorrecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region': {
      id: '/$region'
      path: '/$region'
      fullPath: '/$region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/': {
      id: '/$region/'
      path: '/'
      fullPath: '/$region/'
      preLoaderRoute: typeof RegionIndexRouteImport
      parentRoute: typeof RegionRoute
    }
    '/vitrine/$token': {
      id: '/vitrine/$token'
      path: '/vitrine/$token'
      fullPath: '/vitrine/$token'
      preLoaderRoute: typeof VitrineTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine-pessoal/novo': {
      id: '/vitrine-pessoal/novo'
      path: '/vitrine-pessoal/novo'
      fullPath: '/vitrine-pessoal/novo'
      preLoaderRoute: typeof VitrinePessoalNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publieditorial/$token': {
      id: '/publieditorial/$token'
      path: '/publieditorial/$token'
      fullPath: '/publieditorial/$token'
      preLoaderRoute: typeof PublieditorialTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editoria/$categoria': {
      id: '/editoria/$categoria'
      path: '/editoria/$categoria'
      fullPath: '/editoria/$categoria'
      preLoaderRoute: typeof EditoriaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor/$slug': {
      id: '/autor/$slug'
      path: '/autor/$slug'
      fullPath: '/autor/$slug'
      preLoaderRoute: typeof AutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vitrine-pessoal': {
      id: '/admin/vitrine-pessoal'
      path: '/vitrine-pessoal'
      fullPath: '/admin/vitrine-pessoal'
      preLoaderRoute: typeof AdminVitrinePessoalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/senha': {
      id: '/admin/senha'
      path: '/senha'
      fullPath: '/admin/senha'
      preLoaderRoute: typeof AdminSenhaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regioes': {
      id: '/admin/regioes'
      path: '/regioes'
      fullPath: '/admin/regioes'
      preLoaderRoute: typeof AdminRegioesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos-chat': {
      id: '/admin/pedidos-chat'
      path: '/pedidos-chat'
      fullPath: '/admin/pedidos-chat'
      preLoaderRoute: typeof AdminPedidosChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/painel': {
      id: '/admin/painel'
      path: '/painel'
      fullPath: '/admin/painel'
      preLoaderRoute: typeof AdminPainelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memoria-editorial': {
      id: '/admin/memoria-editorial'
      path: '/memoria-editorial'
      fullPath: '/admin/memoria-editorial'
      preLoaderRoute: typeof AdminMemoriaEditorialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fontes': {
      id: '/admin/fontes'
      path: '/fontes'
      fullPath: '/admin/fontes'
      preLoaderRoute: typeof AdminFontesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clusters': {
      id: '/admin/clusters'
      path: '/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AdminClustersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agentes': {
      id: '/admin/agentes'
      path: '/agentes'
      fullPath: '/admin/agentes'
      preLoaderRoute: typeof AdminAgentesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/classificados': {
      id: '/$region/classificados'
      path: '/classificados'
      fullPath: '/$region/classificados'
      preLoaderRoute: typeof RegionClassificadosRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/$slug': {
      id: '/$region/$slug'
      path: '/$slug'
      fullPath: '/$region/$slug'
      preLoaderRoute: typeof RegionSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap-news.xml': {
      id: '/api/public/sitemap-news.xml'
      path: '/api/public/sitemap-news.xml'
      fullPath: '/api/public/sitemap-news.xml'
      preLoaderRoute: typeof ApiPublicSitemapNewsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss.xml': {
      id: '/api/public/rss.xml'
      path: '/api/public/rss.xml'
      fullPath: '/api/public/rss.xml'
      preLoaderRoute: typeof ApiPublicRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/llms.txt': {
      id: '/api/public/llms.txt'
      path: '/api/public/llms.txt'
      fullPath: '/api/public/llms.txt'
      preLoaderRoute: typeof ApiPublicLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/llms-full.txt': {
      id: '/api/public/llms-full.txt'
      path: '/api/public/llms-full.txt'
      fullPath: '/api/public/llms-full.txt'
      preLoaderRoute: typeof ApiPublicLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/editoria/$categoria': {
      id: '/$region/editoria/$categoria'
      path: '/editoria/$categoria'
      fullPath: '/$region/editoria/$categoria'
      preLoaderRoute: typeof RegionEditoriaCategoriaRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/cidade/$cidade': {
      id: '/$region/cidade/$cidade'
      path: '/cidade/$cidade'
      fullPath: '/$region/cidade/$cidade'
      preLoaderRoute: typeof RegionCidadeCidadeRouteImport
      parentRoute: typeof RegionRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/indexnow/$key': {
      id: '/api/public/indexnow/$key'
      path: '/api/public/indexnow/$key'
      fullPath: '/api/public/indexnow/$key'
      preLoaderRoute: typeof ApiPublicIndexnowKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/indexnow-ping': {
      id: '/api/public/hooks/indexnow-ping'
      path: '/api/public/hooks/indexnow-ping'
      fullPath: '/api/public/hooks/indexnow-ping'
      preLoaderRoute: typeof ApiPublicHooksIndexnowPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss/regiao/$region': {
      id: '/api/public/rss/regiao/$region'
      path: '/api/public/rss/regiao/$region'
      fullPath: '/api/public/rss/regiao/$region'
      preLoaderRoute: typeof ApiPublicRssRegiaoRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss/categoria/$slug': {
      id: '/api/public/rss/categoria/$slug'
      path: '/api/public/rss/categoria/$slug'
      fullPath: '/api/public/rss/categoria/$slug'
      preLoaderRoute: typeof ApiPublicRssCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss/cidade/$region/$cidade': {
      id: '/api/public/rss/cidade/$region/$cidade'
      path: '/api/public/rss/cidade/$region/$cidade'
      fullPath: '/api/public/rss/cidade/$region/$cidade'
      preLoaderRoute: typeof ApiPublicRssCidadeRegionCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegionRouteChildren {
  RegionSlugRoute: typeof RegionSlugRoute
  RegionClassificadosRoute: typeof RegionClassificadosRoute
  RegionIndexRoute: typeof RegionIndexRoute
  RegionCidadeCidadeRoute: typeof RegionCidadeCidadeRoute
  RegionEditoriaCategoriaRoute: typeof RegionEditoriaCategoriaRoute
}

const RegionRouteChildren: RegionRouteChildren = {
  RegionSlugRoute: RegionSlugRoute,
  RegionClassificadosRoute: RegionClassificadosRoute,
  RegionIndexRoute: RegionIndexRoute,
  RegionCidadeCidadeRoute: RegionCidadeCidadeRoute,
  RegionEditoriaCategoriaRoute: RegionEditoriaCategoriaRoute,
}

const RegionRouteWithChildren =
  RegionRoute._addFileChildren(RegionRouteChildren)

interface AdminRouteChildren {
  AdminAgentesRoute: typeof AdminAgentesRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminClustersRoute: typeof AdminClustersRoute
  AdminFontesRoute: typeof AdminFontesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMemoriaEditorialRoute: typeof AdminMemoriaEditorialRoute
  AdminPainelRoute: typeof AdminPainelRoute
  AdminPedidosChatRoute: typeof AdminPedidosChatRoute
  AdminRegioesRoute: typeof AdminRegioesRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSenhaRoute: typeof AdminSenhaRoute
  AdminVitrinePessoalRoute: typeof AdminVitrinePessoalRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentesRoute: AdminAgentesRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminClustersRoute: AdminClustersRoute,
  AdminFontesRoute: AdminFontesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMemoriaEditorialRoute: AdminMemoriaEditorialRoute,
  AdminPainelRoute: AdminPainelRoute,
  AdminPedidosChatRoute: AdminPedidosChatRoute,
  AdminRegioesRoute: AdminRegioesRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSenhaRoute: AdminSenhaRoute,
  AdminVitrinePessoalRoute: AdminVitrinePessoalRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionRoute: RegionRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CorrecoesRoute: CorrecoesRoute,
  PoliticaEditorialRoute: PoliticaEditorialRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WhatsappRoute: WhatsappRoute,
  AutorSlugRoute: AutorSlugRoute,
  EditoriaCategoriaRoute: EditoriaCategoriaRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PublieditorialTokenRoute: PublieditorialTokenRoute,
  RIdRoute: RIdRoute,
  VitrinePessoalNovoRoute: VitrinePessoalNovoRoute,
  VitrineTokenRoute: VitrineTokenRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicLlmsFullDottxtRoute: ApiPublicLlmsFullDottxtRoute,
  ApiPublicLlmsDottxtRoute: ApiPublicLlmsDottxtRoute,
  ApiPublicRssDotxmlRoute: ApiPublicRssDotxmlRoute,
  ApiPublicSitemapNewsDotxmlRoute: ApiPublicSitemapNewsDotxmlRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksIndexnowPingRoute: ApiPublicHooksIndexnowPingRoute,
  ApiPublicIndexnowKeyRoute: ApiPublicIndexnowKeyRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicRssCategoriaSlugRoute: ApiPublicRssCategoriaSlugRoute,
  ApiPublicRssRegiaoRegionRoute: ApiPublicRssRegiaoRegionRoute,
  ApiPublicRssCidadeRegionCidadeRoute: ApiPublicRssCidadeRegionCidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
