/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RegionRouteImport } from './routes/$region'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSenhaRouteImport } from './routes/admin.senha'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminRegioesRouteImport } from './routes/admin.regioes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFontesRouteImport } from './routes/admin.fontes'
import { Route as AdminClustersRouteImport } from './routes/admin.clusters'
import { Route as RegionClassificadosRouteImport } from './routes/$region.classificados'
import { Route as RegionSlugRouteImport } from './routes/$region.$slug'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as RegionEditoriaCategoriaRouteImport } from './routes/$region.editoria.$categoria'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSenhaRoute = AdminSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegioesRoute = AdminRegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFontesRoute = AdminFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClustersRoute = AdminClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AdminRoute,
} as any)
const RegionClassificadosRoute = RegionClassificadosRouteImport.update({
  id: '/classificados',
  path: '/classificados',
  getParentRoute: () => RegionRoute,
} as any)
const RegionSlugRoute = RegionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionEditoriaCategoriaRoute = RegionEditoriaCategoriaRouteImport.update({
  id: '/editoria/$categoria',
  path: '/editoria/$categoria',
  getParentRoute: () => RegionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/admin/': typeof AdminIndexRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/admin': typeof AdminIndexRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/admin/': typeof AdminIndexRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region'
    | '/admin'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/admin/'
    | '/$region/editoria/$categoria'
    | '/api/public/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$region'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/admin'
    | '/$region/editoria/$categoria'
    | '/api/public/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/$region'
    | '/admin'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/admin/'
    | '/$region/editoria/$categoria'
    | '/api/public/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionRoute: typeof RegionRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  WhatsappRoute: typeof WhatsappRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region': {
      id: '/$region'
      path: '/$region'
      fullPath: '/$region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/senha': {
      id: '/admin/senha'
      path: '/senha'
      fullPath: '/admin/senha'
      preLoaderRoute: typeof AdminSenhaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regioes': {
      id: '/admin/regioes'
      path: '/regioes'
      fullPath: '/admin/regioes'
      preLoaderRoute: typeof AdminRegioesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fontes': {
      id: '/admin/fontes'
      path: '/fontes'
      fullPath: '/admin/fontes'
      preLoaderRoute: typeof AdminFontesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clusters': {
      id: '/admin/clusters'
      path: '/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AdminClustersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/classificados': {
      id: '/$region/classificados'
      path: '/classificados'
      fullPath: '/$region/classificados'
      preLoaderRoute: typeof RegionClassificadosRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/$slug': {
      id: '/$region/$slug'
      path: '/$slug'
      fullPath: '/$region/$slug'
      preLoaderRoute: typeof RegionSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/editoria/$categoria': {
      id: '/$region/editoria/$categoria'
      path: '/editoria/$categoria'
      fullPath: '/$region/editoria/$categoria'
      preLoaderRoute: typeof RegionEditoriaCategoriaRouteImport
      parentRoute: typeof RegionRoute
    }
  }
}

interface RegionRouteChildren {
  RegionSlugRoute: typeof RegionSlugRoute
  RegionClassificadosRoute: typeof RegionClassificadosRoute
  RegionEditoriaCategoriaRoute: typeof RegionEditoriaCategoriaRoute
}

const RegionRouteChildren: RegionRouteChildren = {
  RegionSlugRoute: RegionSlugRoute,
  RegionClassificadosRoute: RegionClassificadosRoute,
  RegionEditoriaCategoriaRoute: RegionEditoriaCategoriaRoute,
}

const RegionRouteWithChildren =
  RegionRoute._addFileChildren(RegionRouteChildren)

interface AdminRouteChildren {
  AdminClustersRoute: typeof AdminClustersRoute
  AdminFontesRoute: typeof AdminFontesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRegioesRoute: typeof AdminRegioesRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSenhaRoute: typeof AdminSenhaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClustersRoute: AdminClustersRoute,
  AdminFontesRoute: AdminFontesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRegioesRoute: AdminRegioesRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSenhaRoute: AdminSenhaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionRoute: RegionRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  WhatsappRoute: WhatsappRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
