/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PoliticaEditorialRouteImport } from './routes/politica-editorial'
import { Route as CorrecoesRouteImport } from './routes/correcoes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RegionRouteImport } from './routes/$region'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegionIndexRouteImport } from './routes/$region.index'
import { Route as RIdRouteImport } from './routes/r.$id'
import { Route as AutorSlugRouteImport } from './routes/autor.$slug'
import { Route as AdminSenhaRouteImport } from './routes/admin.senha'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminRegioesRouteImport } from './routes/admin.regioes'
import { Route as AdminPautaRouteImport } from './routes/admin.pauta'
import { Route as AdminPainelRouteImport } from './routes/admin.painel'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFontesRouteImport } from './routes/admin.fontes'
import { Route as AdminClustersRouteImport } from './routes/admin.clusters'
import { Route as AdminAnunciosRouteImport } from './routes/admin.anuncios'
import { Route as RegionClassificadosRouteImport } from './routes/$region.classificados'
import { Route as RegionSlugRouteImport } from './routes/$region.$slug'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicSitemapNewsDotxmlRouteImport } from './routes/api/public/sitemap-news[.]xml'
import { Route as ApiPublicRssDotxmlRouteImport } from './routes/api/public/rss[.]xml'
import { Route as ApiPublicLlmsDottxtRouteImport } from './routes/api/public/llms[.]txt'
import { Route as ApiPublicLlmsFullDottxtRouteImport } from './routes/api/public/llms-full[.]txt'
import { Route as RegionEditoriaCategoriaRouteImport } from './routes/$region.editoria.$categoria'
import { Route as RegionCidadeCidadeRouteImport } from './routes/$region.cidade.$cidade'
import { Route as ApiPublicIndexnowKeyRouteImport } from './routes/api/public/indexnow.$key'
import { Route as ApiPublicHooksIndexnowPingRouteImport } from './routes/api/public/hooks.indexnow-ping'
import { Route as ApiPublicRssRegiaoRegionRouteImport } from './routes/api/public/rss.regiao.$region'
import { Route as ApiPublicRssCategoriaSlugRouteImport } from './routes/api/public/rss.categoria.$slug'
import { Route as ApiPublicRssCidadeRegionCidadeRouteImport } from './routes/api/public/rss.cidade.$region.$cidade'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaEditorialRoute = PoliticaEditorialRouteImport.update({
  id: '/politica-editorial',
  path: '/politica-editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrecoesRoute = CorrecoesRouteImport.update({
  id: '/correcoes',
  path: '/correcoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionRoute = RegionRouteImport.update({
  id: '/$region',
  path: '/$region',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegionIndexRoute = RegionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RegionRoute,
} as any)
const RIdRoute = RIdRouteImport.update({
  id: '/r/$id',
  path: '/r/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutorSlugRoute = AutorSlugRouteImport.update({
  id: '/autor/$slug',
  path: '/autor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSenhaRoute = AdminSenhaRouteImport.update({
  id: '/senha',
  path: '/senha',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegioesRoute = AdminRegioesRouteImport.update({
  id: '/regioes',
  path: '/regioes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPautaRoute = AdminPautaRouteImport.update({
  id: '/pauta',
  path: '/pauta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPainelRoute = AdminPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFontesRoute = AdminFontesRouteImport.update({
  id: '/fontes',
  path: '/fontes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClustersRoute = AdminClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const RegionClassificadosRoute = RegionClassificadosRouteImport.update({
  id: '/classificados',
  path: '/classificados',
  getParentRoute: () => RegionRoute,
} as any)
const RegionSlugRoute = RegionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RegionRoute,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapNewsDotxmlRoute =
  ApiPublicSitemapNewsDotxmlRouteImport.update({
    id: '/api/public/sitemap-news.xml',
    path: '/api/public/sitemap-news.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssDotxmlRoute = ApiPublicRssDotxmlRouteImport.update({
  id: '/api/public/rss.xml',
  path: '/api/public/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLlmsDottxtRoute = ApiPublicLlmsDottxtRouteImport.update({
  id: '/api/public/llms.txt',
  path: '/api/public/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLlmsFullDottxtRoute = ApiPublicLlmsFullDottxtRouteImport.update({
  id: '/api/public/llms-full.txt',
  path: '/api/public/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionEditoriaCategoriaRoute = RegionEditoriaCategoriaRouteImport.update({
  id: '/editoria/$categoria',
  path: '/editoria/$categoria',
  getParentRoute: () => RegionRoute,
} as any)
const RegionCidadeCidadeRoute = RegionCidadeCidadeRouteImport.update({
  id: '/cidade/$cidade',
  path: '/cidade/$cidade',
  getParentRoute: () => RegionRoute,
} as any)
const ApiPublicIndexnowKeyRoute = ApiPublicIndexnowKeyRouteImport.update({
  id: '/api/public/indexnow/$key',
  path: '/api/public/indexnow/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIndexnowPingRoute =
  ApiPublicHooksIndexnowPingRouteImport.update({
    id: '/api/public/hooks/indexnow-ping',
    path: '/api/public/hooks/indexnow-ping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssRegiaoRegionRoute =
  ApiPublicRssRegiaoRegionRouteImport.update({
    id: '/api/public/rss/regiao/$region',
    path: '/api/public/rss/regiao/$region',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssCategoriaSlugRoute =
  ApiPublicRssCategoriaSlugRouteImport.update({
    id: '/api/public/rss/categoria/$slug',
    path: '/api/public/rss/categoria/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRssCidadeRegionCidadeRoute =
  ApiPublicRssCidadeRegionCidadeRouteImport.update({
    id: '/api/public/rss/cidade/$region/$cidade',
    path: '/api/public/rss/cidade/$region/$cidade',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/correcoes': typeof CorrecoesRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/pauta': typeof AdminPautaRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/r/$id': typeof RIdRoute
  '/$region/': typeof RegionIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$region/cidade/$cidade': typeof RegionCidadeCidadeRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/llms-full.txt': typeof ApiPublicLlmsFullDottxtRoute
  '/api/public/llms.txt': typeof ApiPublicLlmsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap-news.xml': typeof ApiPublicSitemapNewsDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/hooks/indexnow-ping': typeof ApiPublicHooksIndexnowPingRoute
  '/api/public/indexnow/$key': typeof ApiPublicIndexnowKeyRoute
  '/api/public/rss/categoria/$slug': typeof ApiPublicRssCategoriaSlugRoute
  '/api/public/rss/regiao/$region': typeof ApiPublicRssRegiaoRegionRoute
  '/api/public/rss/cidade/$region/$cidade': typeof ApiPublicRssCidadeRegionCidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/correcoes': typeof CorrecoesRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/pauta': typeof AdminPautaRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/r/$id': typeof RIdRoute
  '/$region': typeof RegionIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$region/cidade/$cidade': typeof RegionCidadeCidadeRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/llms-full.txt': typeof ApiPublicLlmsFullDottxtRoute
  '/api/public/llms.txt': typeof ApiPublicLlmsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap-news.xml': typeof ApiPublicSitemapNewsDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/hooks/indexnow-ping': typeof ApiPublicHooksIndexnowPingRoute
  '/api/public/indexnow/$key': typeof ApiPublicIndexnowKeyRoute
  '/api/public/rss/categoria/$slug': typeof ApiPublicRssCategoriaSlugRoute
  '/api/public/rss/regiao/$region': typeof ApiPublicRssRegiaoRegionRoute
  '/api/public/rss/cidade/$region/$cidade': typeof ApiPublicRssCidadeRegionCidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$region': typeof RegionRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/contato': typeof ContatoRoute
  '/correcoes': typeof CorrecoesRoute
  '/politica-editorial': typeof PoliticaEditorialRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/whatsapp': typeof WhatsappRoute
  '/$region/$slug': typeof RegionSlugRoute
  '/$region/classificados': typeof RegionClassificadosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/clusters': typeof AdminClustersRoute
  '/admin/fontes': typeof AdminFontesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/painel': typeof AdminPainelRoute
  '/admin/pauta': typeof AdminPautaRoute
  '/admin/regioes': typeof AdminRegioesRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/senha': typeof AdminSenhaRoute
  '/autor/$slug': typeof AutorSlugRoute
  '/r/$id': typeof RIdRoute
  '/$region/': typeof RegionIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$region/cidade/$cidade': typeof RegionCidadeCidadeRoute
  '/$region/editoria/$categoria': typeof RegionEditoriaCategoriaRoute
  '/api/public/llms-full.txt': typeof ApiPublicLlmsFullDottxtRoute
  '/api/public/llms.txt': typeof ApiPublicLlmsDottxtRoute
  '/api/public/rss.xml': typeof ApiPublicRssDotxmlRoute
  '/api/public/sitemap-news.xml': typeof ApiPublicSitemapNewsDotxmlRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/hooks/indexnow-ping': typeof ApiPublicHooksIndexnowPingRoute
  '/api/public/indexnow/$key': typeof ApiPublicIndexnowKeyRoute
  '/api/public/rss/categoria/$slug': typeof ApiPublicRssCategoriaSlugRoute
  '/api/public/rss/regiao/$region': typeof ApiPublicRssRegiaoRegionRoute
  '/api/public/rss/cidade/$region/$cidade': typeof ApiPublicRssCidadeRegionCidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$region'
    | '/admin'
    | '/contato'
    | '/correcoes'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/anuncios'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/painel'
    | '/admin/pauta'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/autor/$slug'
    | '/r/$id'
    | '/$region/'
    | '/admin/'
    | '/$region/cidade/$cidade'
    | '/$region/editoria/$categoria'
    | '/api/public/llms-full.txt'
    | '/api/public/llms.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap-news.xml'
    | '/api/public/sitemap.xml'
    | '/api/public/hooks/indexnow-ping'
    | '/api/public/indexnow/$key'
    | '/api/public/rss/categoria/$slug'
    | '/api/public/rss/regiao/$region'
    | '/api/public/rss/cidade/$region/$cidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/correcoes'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/anuncios'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/painel'
    | '/admin/pauta'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/autor/$slug'
    | '/r/$id'
    | '/$region'
    | '/admin'
    | '/$region/cidade/$cidade'
    | '/$region/editoria/$categoria'
    | '/api/public/llms-full.txt'
    | '/api/public/llms.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap-news.xml'
    | '/api/public/sitemap.xml'
    | '/api/public/hooks/indexnow-ping'
    | '/api/public/indexnow/$key'
    | '/api/public/rss/categoria/$slug'
    | '/api/public/rss/regiao/$region'
    | '/api/public/rss/cidade/$region/$cidade'
  id:
    | '__root__'
    | '/'
    | '/$region'
    | '/admin'
    | '/contato'
    | '/correcoes'
    | '/politica-editorial'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/whatsapp'
    | '/$region/$slug'
    | '/$region/classificados'
    | '/admin/anuncios'
    | '/admin/clusters'
    | '/admin/fontes'
    | '/admin/login'
    | '/admin/painel'
    | '/admin/pauta'
    | '/admin/regioes'
    | '/admin/reset-password'
    | '/admin/senha'
    | '/autor/$slug'
    | '/r/$id'
    | '/$region/'
    | '/admin/'
    | '/$region/cidade/$cidade'
    | '/$region/editoria/$categoria'
    | '/api/public/llms-full.txt'
    | '/api/public/llms.txt'
    | '/api/public/rss.xml'
    | '/api/public/sitemap-news.xml'
    | '/api/public/sitemap.xml'
    | '/api/public/hooks/indexnow-ping'
    | '/api/public/indexnow/$key'
    | '/api/public/rss/categoria/$slug'
    | '/api/public/rss/regiao/$region'
    | '/api/public/rss/cidade/$region/$cidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegionRoute: typeof RegionRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  CorrecoesRoute: typeof CorrecoesRoute
  PoliticaEditorialRoute: typeof PoliticaEditorialRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  WhatsappRoute: typeof WhatsappRoute
  AutorSlugRoute: typeof AutorSlugRoute
  RIdRoute: typeof RIdRoute
  ApiPublicLlmsFullDottxtRoute: typeof ApiPublicLlmsFullDottxtRoute
  ApiPublicLlmsDottxtRoute: typeof ApiPublicLlmsDottxtRoute
  ApiPublicRssDotxmlRoute: typeof ApiPublicRssDotxmlRoute
  ApiPublicSitemapNewsDotxmlRoute: typeof ApiPublicSitemapNewsDotxmlRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicHooksIndexnowPingRoute: typeof ApiPublicHooksIndexnowPingRoute
  ApiPublicIndexnowKeyRoute: typeof ApiPublicIndexnowKeyRoute
  ApiPublicRssCategoriaSlugRoute: typeof ApiPublicRssCategoriaSlugRoute
  ApiPublicRssRegiaoRegionRoute: typeof ApiPublicRssRegiaoRegionRoute
  ApiPublicRssCidadeRegionCidadeRoute: typeof ApiPublicRssCidadeRegionCidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-editorial': {
      id: '/politica-editorial'
      path: '/politica-editorial'
      fullPath: '/politica-editorial'
      preLoaderRoute: typeof PoliticaEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correcoes': {
      id: '/correcoes'
      path: '/correcoes'
      fullPath: '/correcoes'
      preLoaderRoute: typeof CorrecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region': {
      id: '/$region'
      path: '/$region'
      fullPath: '/$region'
      preLoaderRoute: typeof RegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/': {
      id: '/$region/'
      path: '/'
      fullPath: '/$region/'
      preLoaderRoute: typeof RegionIndexRouteImport
      parentRoute: typeof RegionRoute
    }
    '/r/$id': {
      id: '/r/$id'
      path: '/r/$id'
      fullPath: '/r/$id'
      preLoaderRoute: typeof RIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autor/$slug': {
      id: '/autor/$slug'
      path: '/autor/$slug'
      fullPath: '/autor/$slug'
      preLoaderRoute: typeof AutorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/senha': {
      id: '/admin/senha'
      path: '/senha'
      fullPath: '/admin/senha'
      preLoaderRoute: typeof AdminSenhaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regioes': {
      id: '/admin/regioes'
      path: '/regioes'
      fullPath: '/admin/regioes'
      preLoaderRoute: typeof AdminRegioesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pauta': {
      id: '/admin/pauta'
      path: '/pauta'
      fullPath: '/admin/pauta'
      preLoaderRoute: typeof AdminPautaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/painel': {
      id: '/admin/painel'
      path: '/painel'
      fullPath: '/admin/painel'
      preLoaderRoute: typeof AdminPainelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fontes': {
      id: '/admin/fontes'
      path: '/fontes'
      fullPath: '/admin/fontes'
      preLoaderRoute: typeof AdminFontesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clusters': {
      id: '/admin/clusters'
      path: '/clusters'
      fullPath: '/admin/clusters'
      preLoaderRoute: typeof AdminClustersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$region/classificados': {
      id: '/$region/classificados'
      path: '/classificados'
      fullPath: '/$region/classificados'
      preLoaderRoute: typeof RegionClassificadosRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/$slug': {
      id: '/$region/$slug'
      path: '/$slug'
      fullPath: '/$region/$slug'
      preLoaderRoute: typeof RegionSlugRouteImport
      parentRoute: typeof RegionRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap-news.xml': {
      id: '/api/public/sitemap-news.xml'
      path: '/api/public/sitemap-news.xml'
      fullPath: '/api/public/sitemap-news.xml'
      preLoaderRoute: typeof ApiPublicSitemapNewsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss.xml': {
      id: '/api/public/rss.xml'
      path: '/api/public/rss.xml'
      fullPath: '/api/public/rss.xml'
      preLoaderRoute: typeof ApiPublicRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/llms.txt': {
      id: '/api/public/llms.txt'
      path: '/api/public/llms.txt'
      fullPath: '/api/public/llms.txt'
      preLoaderRoute: typeof ApiPublicLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/llms-full.txt': {
      id: '/api/public/llms-full.txt'
      path: '/api/public/llms-full.txt'
      fullPath: '/api/public/llms-full.txt'
      preLoaderRoute: typeof ApiPublicLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$region/editoria/$categoria': {
      id: '/$region/editoria/$categoria'
      path: '/editoria/$categoria'
      fullPath: '/$region/editoria/$categoria'
      preLoaderRoute: typeof RegionEditoriaCategoriaRouteImport
      parentRoute: typeof RegionRoute
    }
    '/$region/cidade/$cidade': {
      id: '/$region/cidade/$cidade'
      path: '/cidade/$cidade'
      fullPath: '/$region/cidade/$cidade'
      preLoaderRoute: typeof RegionCidadeCidadeRouteImport
      parentRoute: typeof RegionRoute
    }
    '/api/public/indexnow/$key': {
      id: '/api/public/indexnow/$key'
      path: '/api/public/indexnow/$key'
      fullPath: '/api/public/indexnow/$key'
      preLoaderRoute: typeof ApiPublicIndexnowKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/indexnow-ping': {
      id: '/api/public/hooks/indexnow-ping'
      path: '/api/public/hooks/indexnow-ping'
      fullPath: '/api/public/hooks/indexnow-ping'
      preLoaderRoute: typeof ApiPublicHooksIndexnowPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss/regiao/$region': {
      id: '/api/public/rss/regiao/$region'
      path: '/api/public/rss/regiao/$region'
      fullPath: '/api/public/rss/regiao/$region'
      preLoaderRoute: typeof ApiPublicRssRegiaoRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss/categoria/$slug': {
      id: '/api/public/rss/categoria/$slug'
      path: '/api/public/rss/categoria/$slug'
      fullPath: '/api/public/rss/categoria/$slug'
      preLoaderRoute: typeof ApiPublicRssCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rss/cidade/$region/$cidade': {
      id: '/api/public/rss/cidade/$region/$cidade'
      path: '/api/public/rss/cidade/$region/$cidade'
      fullPath: '/api/public/rss/cidade/$region/$cidade'
      preLoaderRoute: typeof ApiPublicRssCidadeRegionCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RegionRouteChildren {
  RegionSlugRoute: typeof RegionSlugRoute
  RegionClassificadosRoute: typeof RegionClassificadosRoute
  RegionIndexRoute: typeof RegionIndexRoute
  RegionCidadeCidadeRoute: typeof RegionCidadeCidadeRoute
  RegionEditoriaCategoriaRoute: typeof RegionEditoriaCategoriaRoute
}

const RegionRouteChildren: RegionRouteChildren = {
  RegionSlugRoute: RegionSlugRoute,
  RegionClassificadosRoute: RegionClassificadosRoute,
  RegionIndexRoute: RegionIndexRoute,
  RegionCidadeCidadeRoute: RegionCidadeCidadeRoute,
  RegionEditoriaCategoriaRoute: RegionEditoriaCategoriaRoute,
}

const RegionRouteWithChildren =
  RegionRoute._addFileChildren(RegionRouteChildren)

interface AdminRouteChildren {
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminClustersRoute: typeof AdminClustersRoute
  AdminFontesRoute: typeof AdminFontesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPainelRoute: typeof AdminPainelRoute
  AdminPautaRoute: typeof AdminPautaRoute
  AdminRegioesRoute: typeof AdminRegioesRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSenhaRoute: typeof AdminSenhaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminClustersRoute: AdminClustersRoute,
  AdminFontesRoute: AdminFontesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPainelRoute: AdminPainelRoute,
  AdminPautaRoute: AdminPautaRoute,
  AdminRegioesRoute: AdminRegioesRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSenhaRoute: AdminSenhaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegionRoute: RegionRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ContatoRoute: ContatoRoute,
  CorrecoesRoute: CorrecoesRoute,
  PoliticaEditorialRoute: PoliticaEditorialRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  WhatsappRoute: WhatsappRoute,
  AutorSlugRoute: AutorSlugRoute,
  RIdRoute: RIdRoute,
  ApiPublicLlmsFullDottxtRoute: ApiPublicLlmsFullDottxtRoute,
  ApiPublicLlmsDottxtRoute: ApiPublicLlmsDottxtRoute,
  ApiPublicRssDotxmlRoute: ApiPublicRssDotxmlRoute,
  ApiPublicSitemapNewsDotxmlRoute: ApiPublicSitemapNewsDotxmlRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicHooksIndexnowPingRoute: ApiPublicHooksIndexnowPingRoute,
  ApiPublicIndexnowKeyRoute: ApiPublicIndexnowKeyRoute,
  ApiPublicRssCategoriaSlugRoute: ApiPublicRssCategoriaSlugRoute,
  ApiPublicRssRegiaoRegionRoute: ApiPublicRssRegiaoRegionRoute,
  ApiPublicRssCidadeRegionCidadeRoute: ApiPublicRssCidadeRegionCidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
